"""init tables

Revision ID: ea77d6b31edf
Revises: 
Create Date: 2026-08-03 17:57:38.411226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea77d6b31edf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='用户昵称'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='用户头像'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='验证码ID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('code', sa.String(length=10), nullable=False, comment='验证码'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='验证码类型'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('used', sa.Boolean(), nullable=False, comment='是否使用'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_verification_email_code', 'verification_codes', ['email', 'code'], unique=False)
    op.create_table('auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='账 号ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('provider', sa.String(length=30), nullable=False, comment='登录方式 email/google/wechat'),
    sa.Column('provider_account_id', sa.String(length=255), nullable=True, comment='第三方账号唯一ID'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auth_email', 'auth', ['email'], unique=False)
    op.create_index('idx_auth_provider_account', 'auth', ['provider', 'provider_account_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_auth_provider_account', table_name='auth')
    op.drop_index('idx_auth_email', table_name='auth')
    op.drop_table('auth')
    op.drop_index('idx_verification_email_code', table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_table('users')
    # ### end Alembic commands ###
