"""update goals models

Revision ID: 343ffda296f9
Revises: b6ac498eacae
Create Date: 2026-08-17 11:01:02.171679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '343ffda296f9'
down_revision: Union[str, Sequence[str], None] = 'b6ac498eacae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'ai_context')
    op.drop_column('goals', 'rawInput')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('rawInput', sa.TEXT(), autoincrement=False, nullable=True, comment='原始输入'))
    op.add_column('goals', sa.Column('ai_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='ai上下文'))
    # ### end Alembic commands ###
