"""delete goal agent session models

Revision ID: 7f8d23d4c14f
Revises: a6dc145a1c0a
Create Date: 2026-09-03 17:04:25.711221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f8d23d4c14f'
down_revision: Union[str, Sequence[str], None] = 'a6dc145a1c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_sessions')
    op.drop_table('goal_agent_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_agent_sessions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('pending_plan', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('goal_agent_sessions_goal_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('goal_agent_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('goal_agent_sessions_pkey'))
    )
    op.create_table('agent_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='会话ID'),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('agent_type', postgresql.ENUM('goal_planning', 'tutor', 'review', name='agent_type'), autoincrement=False, nullable=False, comment='agent类型'),
    sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='目标ID'),
    sa.Column('stage', sa.VARCHAR(), autoincrement=False, nullable=False, comment='会话阶段'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'active', 'paused', 'completed', 'failed', name='agent_session_status'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('agent_sessions_goal_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_sessions_pkey'))
    )
    # ### end Alembic commands ###
