"""add agent session models

Revision ID: a6dc145a1c0a
Revises: ca45939e967d
Create Date: 2026-09-02 14:57:38.392473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a6dc145a1c0a'
down_revision: Union[str, Sequence[str], None] = 'ca45939e967d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    agent_type = sa.Enum(
        "goal_planning", "tutor", "review", name="agent_type"
    )
    session_status = sa.Enum(
        "pending", "active", "paused", "completed", "failed", name="agent_session_status"
    )
    op.create_table(
        "agent_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="会话ID"),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("agent_type", agent_type, nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=True),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", session_status, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_sessions")
    op.execute("DROP TYPE IF EXISTS agent_session_status")
    op.execute("DROP TYPE IF EXISTS agent_type")
    # ### end Alembic commands ###
