"""update goals models

Revision ID: a80e881391ee
Revises: ded1095c7275
Create Date: 2026-08-14 11:27:14.965802

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a80e881391ee"
down_revision: Union[str, Sequence[str], None] = "ded1095c7275"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("goals", sa.Column("target_date", sa.Date(), nullable=True))
    op.add_column(
        "goals", sa.Column("available_time", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "goals",
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", name="goal_priority"),
            nullable=True,
            comment="优先级",
        ),
    )
    op.add_column("goals", sa.Column("preferences", sa.Text(), nullable=True))
    op.add_column("goals", sa.Column("constraints", sa.Text(), nullable=True))
    op.add_column(
        "goals", sa.Column("rawInput", sa.Text(), nullable=True, comment="原始输入")
    )
    op.add_column(
        "goals", sa.Column("ai_summary", sa.Text(), nullable=True, comment="AI分析结果")
    )
    op.add_column(
        "goals",
        sa.Column(
            "ai_context",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="ai上下文",
        ),
    )

    goal_status = sa.Enum(
        "draft",
        "active",
        "paused",
        "completed",
        "archived",
        name="goal_status",
    )

    # 1. 先在 PostgreSQL 创建枚举类型
    goal_status.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "goals",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=goal_status,
        existing_nullable=False,
        postgresql_using="status::goal_status",
    )
    op.create_index(op.f("ix_goals_priority"), "goals", ["priority"], unique=False)
    op.create_index(op.f("ix_goals_status"), "goals", ["status"], unique=False)
    op.drop_column("goals", "motivation")
    op.drop_column("goals", "end_date")
    op.drop_column("goals", "period")
    op.drop_column("goals", "level")
    op.drop_column("goals", "preference")
    op.drop_column("goals", "daily_hours")
    op.drop_column("goals", "start_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "goals", sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "goals",
        sa.Column(
            "daily_hours",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
            comment="每天投入小时数",
        ),
    )
    op.add_column(
        "goals",
        sa.Column(
            "preference",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="偏好学习方式",
        ),
    )
    op.add_column(
        "goals",
        sa.Column(
            "level",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
            comment="当前水平",
        ),
    )
    op.add_column(
        "goals",
        sa.Column(
            "period",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
            comment="目标周期",
        ),
    )
    op.add_column(
        "goals", sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "goals",
        sa.Column(
            "motivation",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
            comment="学习动机",
        ),
    )
    op.drop_index(op.f("ix_goals_status"), table_name="goals")
    op.drop_index(op.f("ix_goals_priority"), table_name="goals")
    op.alter_column(
        "goals",
        "status",
        existing_type=sa.Enum(
            "draft", "active", "paused", "completed", "archived", name="goal_status"
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_column("goals", "ai_context")
    op.drop_column("goals", "ai_summary")
    op.drop_column("goals", "rawInput")
    op.drop_column("goals", "constraints")
    op.drop_column("goals", "preferences")
    op.drop_column("goals", "priority")
    op.drop_column("goals", "available_time")
    op.drop_column("goals", "target_date")
    # ### end Alembic commands ###
