"""update goals models

Revision ID: b6ac498eacae
Revises: a80e881391ee
Create Date: 2026-08-17 10:51:58.692335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ac498eacae'
down_revision: Union[str, Sequence[str], None] = 'a80e881391ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('duration', sa.Integer(), nullable=True))
    op.drop_column('goals', 'ai_summary')
    op.drop_column('goals', 'target_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('goals', sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True, comment='AI分析结果'))
    op.drop_column('goals', 'duration')
    # ### end Alembic commands ###
