"""add servaral goals attributes

Revision ID: ded1095c7275
Revises: 262a1c585b44
Create Date: 2026-08-13 15:04:43.584214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded1095c7275'
down_revision: Union[str, Sequence[str], None] = '262a1c585b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('period', sa.String(length=20), nullable=False, comment='目标周期'))
    op.add_column('goals', sa.Column('daily_hours', sa.Float(), nullable=False, comment='每天投入小时数'))
    op.add_column('goals', sa.Column('preference', sa.JSON(), nullable=True, comment='偏好学习方式'))
    op.add_column('goals', sa.Column('motivation', sa.String(length=20), nullable=True, comment='学习动机'))
    op.alter_column('goals', 'level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='当前水平')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='当前水平')
    op.drop_column('goals', 'motivation')
    op.drop_column('goals', 'preference')
    op.drop_column('goals', 'daily_hours')
    op.drop_column('goals', 'period')
    # ### end Alembic commands ###
